services:
  mongodb:
    image: mongo/imdb-db
    container_name: mongo-imdb-db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - ./data/mongodb:${MONGO_DIR}/input
    environment:
      MONGO_DIR: ${MONGO_DIR}
    working_dir: ${MONGO_DIR}
